server:
  port: 1802
  compression:
    min-response-size: 2048
    enabled: true
  forward-headers-strategy: native
  servlet:
    context-path: /api

management:
  server:
    port: 1803
    base-path: /api
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      # see: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.files.importing-extensionless
      - configtree:secrets/
  jpa:
    properties:
      hibernate:
        generate_statistics: false
  docker:
    compose:
      lifecycle-management: start_only
# hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=${VAL:12}

db-scheduler:
  enabled: true
  table-name: "SYSTEM.SCHEDULED_TASKS"


system:
  liquibase:
    change-log: classpath:db/system/db.changelog-master.xml
    default-schema: system
    liquibase-schema: system

logging:
  level:
#    org.hibernate.stat: DEBUG
    org.springframework.security: DEBUG
    com.com.dntech: DEBUG

auth0:
  userInfoUri: ${AUTH0_USER_INFO_URI:https://dntech.eu.auth0.com}
  domain: ${AUTH0_DOMAIN}
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}

messaging:
  resource-management-exchange: cozy.resource.management
  booking-processing-exchange: cozy.booking.processing

services:
  account:
    enabled: true
    name: account
    liquibase:
      change-log: classpath:db/account/db.changelog-master.xml
      default-schema: account_service
      liquibase-schema: account_service
    domain:
      globalSettings:
        language: "en"
        timezone: "Berlin/Europe"
        currency: "EUR"

  command:
    enabled: true
    name: command
    liquibase:
      change-log: classpath:db/command/db.changelog-master.xml
      default-schema: command_service
      liquibase-schema: command_service


db-scheduler-log:
  enabled: true
  table-name: "SYSTEM.SCHEDULED_EXECUTION_LOGS"
